<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.14.0a5 on win32)" generated="2025-03-10T21:20:55.208527" rpa="false" schemaversion="5">
<suite id="s1" name="Caso De Test" source="c:\Users\junio\OneDrive\Área de Trabalho\API_Advanced\caso_de_test.robot">
<test id="s1-t1" name="Caso de cenario 01: Validar GET products" line="14">
<kw name="Criar sessão na Advantage">
<msg time="2025-03-10T21:20:55.282552" level="FAIL">No keyword with name 'Criar sessão na Advantage' found.</msg>
<status status="FAIL" start="2025-03-10T21:20:55.282332" elapsed="0.001484">No keyword with name 'Criar sessão na Advantage' found.</status>
</kw>
<kw name="GET Products /search">
<status status="NOT RUN" start="2025-03-10T21:20:55.284507" elapsed="0.000181"/>
</kw>
<kw name="Validar Status Code">
<status status="NOT RUN" start="2025-03-10T21:20:55.285130" elapsed="0.000130"/>
</kw>
<status status="FAIL" start="2025-03-10T21:20:55.279881" elapsed="0.005831">No keyword with name 'Criar sessão na Advantage' found.</status>
</test>
<status status="FAIL" start="2025-03-10T21:20:55.214591" elapsed="0.072516"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Caso De Test" id="s1" pass="0" fail="1" skip="0">Caso De Test</stat>
</suite>
</statistics>
<errors>
<msg time="2025-03-10T21:20:55.252542" level="ERROR">Error in file 'c:\Users\junio\OneDrive\Área de Trabalho\API_Advanced\caso_de_test.robot' on line 2: Importing library 'requestsLibrary' failed: ModuleNotFoundError: No module named 'requestsLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src\robotframework_debug_adapter
  C:\Users\junio\OneDrive\Área de Trabalho\API_Advanced
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src\robotframework_ls\vendored
  C:\Users\junio\AppData\Local\Programs\Python\Python314\python314.zip
  C:\Users\junio\AppData\Local\Programs\Python\Python314\DLLs
  C:\Users\junio\AppData\Local\Programs\Python\Python314\Lib
  C:\Users\junio\AppData\Local\Programs\Python\Python314
  C:\Users\junio\AppData\Local\Programs\Python\Python314\Lib\site-packages</msg>
<msg time="2025-03-10T21:20:55.264892" level="ERROR">Error in file 'c:\Users\junio\OneDrive\Área de Trabalho\API_Advanced\caso_de_test.robot' on line 4: Importing library 'JSONLibrary' failed: ModuleNotFoundError: No module named 'JSONLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src\robotframework_debug_adapter
  C:\Users\junio\OneDrive\Área de Trabalho\API_Advanced
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src
  c:\Users\junio\.vscode\extensions\robocorp.robotframework-lsp-1.13.0\src\robotframework_ls\vendored
  C:\Users\junio\AppData\Local\Programs\Python\Python314\python314.zip
  C:\Users\junio\AppData\Local\Programs\Python\Python314\DLLs
  C:\Users\junio\AppData\Local\Programs\Python\Python314\Lib
  C:\Users\junio\AppData\Local\Programs\Python\Python314
  C:\Users\junio\AppData\Local\Programs\Python\Python314\Lib\site-packages</msg>
<msg time="2025-03-10T21:20:55.277944" level="ERROR">Error in file 'c:\Users\junio\OneDrive\Área de Trabalho\API_Advanced\caso_de_test.robot' on line 6: Resource file 'Automacao_Advantage.robot' does not exist.</msg>
</errors>
</robot>
